apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
  labels:
    app: players
spec:
  replicas: 3
  selector:
    matchLabels:
      app: players
    spec:
      containers:
      - name: playerapp
        image: phijojo/playerapp:latest
        ports:
        - containerPort: 8080
