apiVersion: v1
kind: Service
metadata:
  name: playerapp-svc
  labels:
    app: playerapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: playerapp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: playerapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: playerapp
    spec:
      containers:
      - name: playerapp
        image: phijojo/playerapp:latest
        ports:
        - containerPort: 8080
